// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnjyQ9s6mVol8PO2b8D2wozNjLAodLTU',
    appId: '1:850924075877:web:bfb3b2fed348a592aabf8c',
    messagingSenderId: '850924075877',
    projectId: 'client-prayogi-spkahp',
    authDomain: 'client-prayogi-spkahp.firebaseapp.com',
    storageBucket: 'client-prayogi-spkahp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Rdx7zEYQnkeRxuJp5yN3I1bw2pxuYO4',
    appId: '1:850924075877:android:ad5ed6aa2da80f7eaabf8c',
    messagingSenderId: '850924075877',
    projectId: 'client-prayogi-spkahp',
    storageBucket: 'client-prayogi-spkahp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-VU_GJIEzt1EqfEN02HZ5lhiVQqsOhw',
    appId: '1:850924075877:ios:04ae8f4386e8d4d5aabf8c',
    messagingSenderId: '850924075877',
    projectId: 'client-prayogi-spkahp',
    storageBucket: 'client-prayogi-spkahp.appspot.com',
    iosBundleId: 'com.example.desktopAppPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7-VU_GJIEzt1EqfEN02HZ5lhiVQqsOhw',
    appId: '1:850924075877:ios:04ae8f4386e8d4d5aabf8c',
    messagingSenderId: '850924075877',
    projectId: 'client-prayogi-spkahp',
    storageBucket: 'client-prayogi-spkahp.appspot.com',
    iosBundleId: 'com.example.desktopAppPos',
  );
}
